#!/bin/sh

# set root pointer
xsetroot -cursor_name left_ptr

#picom 
pkill picom
picom -b &

# dunst
pkill dunst
dunst &

# key bindings
sxhkd -c "$HOME/.config/bspwm/sxhkdrc" &

# polybar
$HOME/.config/polybar/launch.sh

# set some bsp specific
bspc monitor -d 1 2 3 4 5 6 7   

bspc config window_gap 8 
bspc config border_width 2
bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
